export default {
  doughnutChartConfig: {
    caption: "Purchase",
    captionFontBold: "0",
    captionFontSize: "14",
    captionFontColor: "#8091ab",
    baseFontColor: "#ffffff",
    baseFont: "basefont-regular",
    baseFontSize: "14",
    baseFontBold: "0",
    chartBottomMargin: "0",
    chartTopMargin: "0",
    chartLeftMargin: "0",
    chartRightMargin: "0",
    canvasBottomMargin: "0",
    canvasTopMargin: "0",
    canvasRightMargin: "0",
    canvasLeftMargin: "0",
    showBorder: "0",
    bgAlpha: "0",
    canvasBgAlpha: "0",
    showLabels: "0",
    showValues: "0",
    paletteColors: "#7A65F1, #ffffff",
    use3DLighting: "0",
    showPlotBorder: "0",
    defaultCenterLabel: "75%",
    pieRadius: "45",
    doughnutRadius: "33",
    showTooltip: "0",
    enableRotation: "0",
    enableSlicing: "0",
    startingAngle: "90"
  },
  doughnutChartData: [
    { label: "active", value: "75" },
    { label: "inactive", value: "25", alpha: "10" }
  ],
  mapChartConfig: {
    bgalpha: "0",
    canvasBgAlpha: "0",
    chartBottomMargin: "0",
    canvasBottomMargin: "0",
    chartTopMargin: "0",
    canvasTopMargin: "0",
    chartLeftMargin: "0",
    canvasLeftMargin: "0",
    chartRightMargin: "0",
    canvasRightMargin: "0",
    showCanvasBorder: "0",
    showLabels: "0",
    caption: "Orders Trend",
    subCaption: "By Geography",
    captionFontBold: "0",
    captionFontSize: "20",
    subCaptionFontSize: "14",
    captionFontColor: "#8091ab",
    baseFont: "basefont-regular",
    baseFontSize: "14",
    baseFontColor: "#8091ab",
    baseFontBold: "0",
    captionAlignment: "left"
  }
};
